### ISSUE TITLE
Level 1 -> Part 6 -> Build your webhook 

### ISSUE THREAD

**Issue by Aishuav01** [actions-on-google/codelabs-nodejs#23] opened 2018-10-02 10:26 UTC
https://codelabs.developers.google.com/codelabs/actions-1/index.html?index=..%2F..%2Findex#5
In level 1 , Under Implement a webhook (part 6)
* Under build your webhook
*4th step missing or written as 5
*while testint the app , it does not work

![codelabs](https://user-images.githubusercontent.com/26162392/46343541-b5d8ad80-c65b-11e8-9e78-658c20261b09.png)

*It shows the above response as "test app not reponding"
*I have replaced the index.js with the given code but it is not working

**Comment by mleonelli** [comment] 2018-11-29 15:19
@Aishuav01 if the issue is closed for you (and the instructions seem to be correct now), could you please close it here in Github?

**Comment by smishra2** [comment] 2018-12-19 03:58
@Thanks @mleonelli and @Aishuav01, I'm closing now. But please reopen if the issues persists.

**Closed by smishra2** 2018-12-19 03:58 UTC
